workspace = { members = ["generics_q3", "generics_q4", "generics_q5"] }
[package]
name = "generics_q2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
